### PR TITLE
Feat: add store for bridge

### PR DESCRIPTION
**Pull request by phultquist**
Creates the `getStoryblokBridge` store to allow better DX to listen to live updates with Storyblok.

Stores with auto-subscriptions make it really easy to subscribe to content that changes often. [Here's a demo](https://storyblok-demo-gilt.vercel.app/) of the starter app with stores!

### CODE REVIEW

**Comment by phultquist** [comment]
Hey, Alex! 👋

I think we might be already there. The reason that we have a two-line solution right now is because the initial props, which are fed from the server. Initial data is useful to help prevent CLS, and for SEO. But, we can always set the `initialStory` to undefined, and wait until that store is populated (like the React SDK):

```js
let story = getStoryblokBridge(myStoryId, undefined);
```

Note that this won't get you the content on the page initially — and it has to be that way, since server side props have to be serializable.

As for the name, we can certainly rename it to `useStoryblok` — I'll update the name of the fn to reflect that. @alexjoverm 

And yes, this will work with SvelteKit! The current one already does — but the initial story needs to be provided from the server — otherwise, we don't get any of the benefits from SvelteKit (SEO, for example).

The same is true in React/Next.JS. In order to populate the page with HTML before the React DOM takes over, we'd have to supply an initial story [just like the Next.JS example](https://github.com/storyblok/storyblok-react/blob/f336c6a6a822e3d85532836e4658642263e88940/README.md?plain=1#L171-L202).

That is, the example in [the example demo](https://github.com/phultquist/storyblok-demo/blob/550bafb85797011f56ac7a3109fa6f8b2c49a6ed/src/routes/index.svelte#L21) has two lines because of the initial data, just like the Next.JS example above — in this case, we're replacing the `getStaticProps` with the `load` function (though that's been moved in the latest versions of SvelteKit).

Let me know if this all makes sense... I'd be happy to show a demo!

**Comment by phultquist** [comment]
Update: it's been renamed!

**Comment by josefineschaefer** [comment]
Amazing, thank you @phultquist !
We had some internal discussions on naming things, and finally could agree on the following suggestion: could you please rename "useStoryblok" to "subscribeStoryblokBridge"? 
This way, we don't break in consistency with the other frameworks and hopefully it becomes more clear what the function will do. Thanks!

**Comment by spences10** [comment]
Just a heads up! I cancelled the workflow as it was running for well over 2hrs

**Pull request merged**
